// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBCvRgUVU8-L4LBDM10NwNfseM4In6OpI',
    appId: '1:1049938272173:web:4bcc64660606b5ee500b24',
    messagingSenderId: '1049938272173',
    projectId: 'hypee-ffbed',
    authDomain: 'hypee-ffbed.firebaseapp.com',
    storageBucket: 'hypee-ffbed.appspot.com',
    measurementId: 'G-Z2F13S2KNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvbZuoVygFxCaIxOhuODmfrKbPIK2LHtM',
    appId: '1:1049938272173:android:6bbe74dfa8f6de6a500b24',
    messagingSenderId: '1049938272173',
    projectId: 'hypee-ffbed',
    storageBucket: 'hypee-ffbed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0BhqTnkh5PBc0S_vWi6oN6wZhA6xUFwE',
    appId: '1:1049938272173:ios:5b22900529d79f19500b24',
    messagingSenderId: '1049938272173',
    projectId: 'hypee-ffbed',
    storageBucket: 'hypee-ffbed.appspot.com',
    androidClientId: '1049938272173-00ikp8dq9cjb0b0thpndgrt163jk8sua.apps.googleusercontent.com',
    iosClientId: '1049938272173-5gaj8r9v5vvksvu84ae1p9n8d6tmpph6.apps.googleusercontent.com',
    iosBundleId: 'com.example.hypee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0BhqTnkh5PBc0S_vWi6oN6wZhA6xUFwE',
    appId: '1:1049938272173:ios:a348727420252be3500b24',
    messagingSenderId: '1049938272173',
    projectId: 'hypee-ffbed',
    storageBucket: 'hypee-ffbed.appspot.com',
    androidClientId: '1049938272173-00ikp8dq9cjb0b0thpndgrt163jk8sua.apps.googleusercontent.com',
    iosClientId: '1049938272173-1h7nl14uii8iaj6l7tu1m2sq6gej825s.apps.googleusercontent.com',
    iosBundleId: 'com.example.hypeeContentCreator',
  );
}
